# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170904_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='speed',
            field=models.FloatField(max_length=1000),
        ),
    ]
